
filebeat.inputs:
  - type: log
    paths:
      - /var/log/data.log*
    json.keys_under_root: true
    json.add_error_key: true

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:es01:9200}'
  username: '${ELASTICSEARCH_USERNAME:elastic}'
  password: '${ELASTICSEARCH_PASSWORD:changeme}'